test

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -46,7 +46,7 @@ jobs:
       - name: Generate README
         run: |
           project_name=$(echo "${{ inputs.library }}" | sed -e 's/-/ /g' -e "s/\b\(.\)/\u\1/g")
-          echo -e "# $project_name\nThe sources for this package are in the main [$project_name](https://github.com/${{ env.GITHUB_REPOSITORY }}) repo. Please file issues and pull requests against that repo." >> README.md
+          echo -e "# $project_name\nThe sources for this package are in the main [$project_name](https://github.com/${{ env.GITHUB_REPOSITORY }}) repo. Please file issues and pull requests against that repo." >> ./projects/${{ inputs.library }}/README.md
 
       # Setup the requirement for npm package
       - name: Set up Node.js
@@ -88,22 +88,22 @@ jobs:
           ORG=${{ github.repository_owner }}
           PACKAGE_NAME=${{ inputs.library }}
           PACKAGE_VERSION=${{ inputs.package_version }}
-          
+
           response=$(curl -s -w "%{http_code}" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
             "https://api.github.com/orgs/${ORG}/packages/npm/${PACKAGE_NAME}/versions")
-          
+
           # Extract HTTP status code
           status_code="${response: -3}"
-          
+
           # Check if the request was successful (status code 2xx)
           if [[ $status_code -eq 200 ]]; then
             # Fetch response body
             response_body=$(echo "${response}" | sed '$s/...$//')
-          
+
             # Parse JSON response with jq to find the version ID
             version_id=$(echo "${response_body}" | jq -r --arg PACKAGE_VERSION "${PACKAGE_VERSION}" '
             .[] | select(.name | startswith($PACKAGE_VERSION)) | .id')
-          
+
             # Check if version_id is not empty
             if [[ -n "${version_id}" ]]; then
               echo "Version ID found: ${version_id}"
@@ -117,19 +117,28 @@ jobs:
             echo "version_id=0" >> $GITHUB_OUTPUT
           fi
 
-      - name: Debug Info
-        run: |
-          echo "github.ref: ${{ github.ref }}"
-          echo "steps.version-id.outputs.result: ${{ steps.version-id.outputs.version_id }}"
-        
       # Remove previous push of that version
       - name: Delete package
         if: ${{ !(startsWith(github.ref, 'refs/tags/v')) && steps.version-id.outputs.version_id != '0' }}
-        uses: actions/delete-package-versions@v5
-        with:
-          package-name: ${{ inputs.library }}
-          package-type: "npm"
-          package-version-ids: ${{ steps.version-id.outputs.result }}
+        run: |
+          ORG=${{ github.repository_owner }}
+          PACKAGE_NAME=${{ inputs.library }}
+          VERSION_ID=${{ steps.version-id.outputs.version_id }}
+
+          # Delete the package version using GitHub API
+          response=$(curl -s -w "%{http_code}" -X DELETE -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+            "https://api.github.com/orgs/${ORG}/packages/npm/${PACKAGE_NAME}/versions/${VERSION_ID}")
+
+          # Extract HTTP status code
+          status_code="${response: -3}"
+
+          # Check if the request was successful (status code 2xx)
+          if [[ $status_code -eq 204 ]]; then
+            echo "Package version deleted successfully."
+          else
+            echo "Failed to delete package version. HTTP status code: $status_code"
+            exit 1
+          fi
 
       # Publish the package.
       # If it's from a git tag, the package is published to npmjs.com and
