test

diff --git a/.github/workflows/projects.yml b/.github/workflows/projects.yml
--- a/.github/workflows/projects.yml
+++ b/.github/workflows/projects.yml
@@ -44,11 +44,18 @@ jobs:
           # Get the reference based on the event type
           if [[ "$GITHUB_EVENT_NAME" == "pull_request" ]]; then
             pullRequestNumber=$GITHUB_EVENT_PULL_REQUEST_NUMBER
-            response=$(curl -v -s -H "Authorization: Bearer ${{ secrets.WORKFLOW_TOKEN }}" \
+            response=$(curl -s -w "%{http_code}" -v -H "Authorization: Bearer ${{ secrets.WORKFLOW_TOKEN }}" \
               "https://api.github.com/repos/$owner/$repo/pulls/$pullRequestNumber")
+            status_code=${response:${#response}-3}
             ref=$(echo "$response" | jq -r '.head.ref')
+            
+            # Check if the HTTP status code is not in the 2xx range
+            if [[ "$status_code" != "200" ]]; then
+              echo "Failed to fetch pull request details. HTTP status code: $status_code"
+              exit 1
+            fi
           else
-            if [[ $GITHUB_REF == refs/tags/* ]]; then
+            if [[ "$GITHUB_REF" == refs/tags/* ]]; then
               ref=${GITHUB_REF#refs/tags/}
             else
               ref=${GITHUB_REF#refs/heads/}
@@ -66,8 +73,8 @@ jobs:
               -H "Authorization: Bearer ${{ secrets.WORKFLOW_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               "https://api.github.com/repos/$owner/$repo/actions/workflows/$workflow_id/dispatches" \
-              -d "{\"ref\":\"$ref\", \"inputs\":{\"library\":\"$library\", \"registry\":\"${{ steps.package-meta.outputs.registry }}\", \"registry_secret\":\"${{ steps.package-meta.outputs.secret }}\", \"package_name\":\"$owner/$library\", \"package_version\":\"${{ steps.package-meta.outputs.version }}\"}")
-          
+              -d "{\"ref\":\"$ref\", \"inputs\":{\"library\":\"$library\", \"registry\":\"${{ steps.package-meta.outputs.registry }}\", \"registry_secret\":\"${{ steps.package-meta.outputs.secret }}\", \"package_name\":\"$library\", \"package_version\":\"${{ steps.package-meta.outputs.version }}\"}")
+            
             # Check if the HTTP status code is not in the 2xx range
             if [[ "${response:${#response}-3}" != "200" ]]; then
               echo "Failed to trigger workflow for $library. HTTP status code: ${response:${#response}-3}"
